### ISSUE TITLE
Missing error handling...

### ISSUE THREAD

**Issue by paul90** [WardCunningham/wiki-plugin-plugmatic#7]
On start-up the plugin makes a request to github

https://github.com/WardCunningham/wiki-plugin-plugmatic/blob/83b1c99199b3fe7339f0d8dacbb385ae393bdaf4/server/server.coffee#L33

There appears to be no error handling, which might be causing the problem seen in fedwiki/wiki#112

As an aside, this will be performed for each wiki in a farm as it starts - this sort of admin plugin would probably be better served with a per farm component, rather than per wiki.

**Comment by WardCunningham** [comment]
I will make this request on demand, once for each app running on a server. And I will handle errors by just not making the data available to the client which will have to tolerate that circumstance by leaving the package column blank.

**Comment by WardCunningham** [comment]
Resolved by #8.
